#
# Energy readers and parsers toolkit
# Copyright (C) 2019-2023 Niels Basjes
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Energy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Java 17
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sourcecode
      uses: actions/checkout@v3

    - name: Cache Local Maven Repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-


    - name: 'Setup: Install JDK 8 & 17'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: |
          8
          17

    - name: Build
      run: mvn -B install

    - name: 'Codecov'
      uses: codecov/codecov-action@v3.1.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
